### ISSUE TITLE
Main highlight color doesn't change in some apps (gtk-theme-config)

### ISSUE THREAD

**Issue by vitalykorolev** [shimmerproject/Numix#165]
This seems to be a regression as it used to work nicely with all apps before. I'm not sure when it changed, but now some apps do not follow the color set by gtk-theme-config. (i.e. highlight remains red) For example, Synaptic Package Manager has this issue. (I know window controls can't follow this settings due to theme engine limitation.)

**Comment by khurshid-alam** [comment]
Already fixed.
